language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install
  - composer update
  - wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.0.jar
  - cp .env.example .env
  - mysql -u root < "CREATE DATABASE pairup DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';GRANT ALL PRIVILEGES ON pairup.* TO 'homestead'@'localhost';FLUSH PRIVILEGES;"
  - php artisan key:generate
  - php artisan migrate:install
  - php artisan migrate:status
  - php artisan migrate
  - java -jar selenium-server-standalone-2.47.0.jar
  - php artisan serve