language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install
  - composer update
  - wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.0.jar