language: php

php:
  - 5.5

before_install:
  - mysql -e "CREATE DATABASE pairup DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;CREATE USER 'pairup'@'localhost' IDENTIFIED BY 'secret';GRANT ALL PRIVILEGES ON pairup.* TO 'pairup'@'localhost';FLUSH PRIVILEGES;" -uroot

before_script:
  - composer self-update
  - composer install
  - composer update
  - wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.0.jar
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate:install
  - php artisan migrate:status
  - php artisan migrate
  - java -jar selenium-server-standalone-2.47.0.jar
  - php artisan serve